apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-359710
  artifacts:
    - image: manelcastro/client-test
      # - image: us.gcr.io/ticketing-dev-359710/client
      context: client-test
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    # - image: manelcastro/tickets
    #   # - image: us.gcr.io/ticketing-dev-359710/tickets
    #   context: tickets
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .

    # - image: manelcastro/expiration
    #   # - image: us.gcr.io/ticketing-dev-359710/expiration
    #   context: expiration
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
