
name: deploy-client

on:
  push: #if merge actually counts as push
    branches:
      - main
    paths:
      - "client-test/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
      
    - name: 'Set project in gcloud CLI'
      run: 'gcloud config set project idyllic-lotus-378515'
      
    - id: 'get-credentials'
      name: 'get credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: 'cluster-1'
        location: 'us-central1-c'
        
    # The KUBECONFIG env var is automatically exported and picked up by kubectl.
    - id: 'get-pods'
      name: 'get-pods'
      run: 'kubectl get pods'
      
    - name: 'login to docker'
      run: 'docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        #https://docs.docker.com/docker-hub/access-tokens/
      
    #  run: cd ticketing/client && docker build -t manelcastro/client .
    # - 
    #  - run: docker push manelcastro/client

      
  
      
      

