
name: deploy-client

on:
  push: #if merge actually counts as push
    branches:
      - main
    paths:
      - "client-test/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
