
name: deploy-client

on:
  push: #if merge actually counts as push
    branches:
      - main
    paths:
      - "client-test/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
      
    - name: 'Set project in gcloud CLI'
      run: 'gcloud config set project idyllic-lotus-378515'
      
    - name: 'Set project location in gcloud CLI'
      run: 'gcloud config set compute/location us-central1-c'
      
    - name: 'to work specifically with this cluster'
      run: 'gcloud container clusters get-credentials cluster-1'
      
      

